This folder has source codes related to the Dual Degree Project - "A computational study of spin-dependent current flow through quantum wires" done by Alfred Ajay Aureate R. under the guidance of Prof. Anil Prabhakar, Dept. of Electrical Engineering, IITM during June - May 2015.

Please refer "EE10B052.pdf" document for a detailed description of the project.

The source code could be divided into three parts:
i) Simulation of quantum wire					- corresponds to the folders "sim_fdm", "sim_lobpcg", "sim_mesh" and "sim_vsm"
ii) Studying TMR for a quantum wire structure	- corresponds to the folder "tmr"
iii) Studying STT for a quantum wire structure	- corresponds to the folder "stt"

The libraries required for proper functioning of the code are: matplotlib, numpy, scipy, pyamg and pylab. For mesh related simulations, some additional libraries are also required: fipy with Gmsh and mayavi (Mayavi2)


Structural description of the source code:

/DDP_codes/sim_vsm/sqw/vsm_sqw_sim_err.py		- Simulation of wave function using variable separation method for square quantum wire and the 													  error compared to the analytical solution
/DDP_codes/sim_vsm/sqw/vsm_sqw_err_blocks.py	- Error in the simulation of wave function using variable separation method for square quantum 													  wire as the number of blocks is varied

/DDP_codes/sim_vsm/cqw/vsm_cqw_sim_err.py		- Simulation of wave function using variable separation method for circular quantum wire and 													  error compared to the analytical solution


/DDP_codes/sim_fdm/sqw/fdm_sqw_sim_err_iter.py 	- Simulation of wave function using finite difference method for square quantum wire and the 													  error compared to the analytical solution

/DDP_codes/sim_fdm/cqw/fdm_cqw_sim_err_iter.py 	- Simulation of wave function using finite difference method for circular quantum wire and the 													  error compared to the analytical solution


/DDP_codes/sim_mesh/square_qw/sqw.py			- Simulation of wave function using standard volume approach for square quantum wire geometry 													  mesh generated by Gmsh and visualized

/DDP_codes/sim_mesh/circular_qw/cqw.py			- Simulation of wave function using standard volume approach for circular quantum wire 													  geometry mesh generated by Gmsh and visualized

/DDP_codes/sim_mesh/cube_qd/cubeqd.py			- Simulation of wave function using standard volume approach for cubical quantum dot geometry 													  mesh generated by Gmsh and visualized using Mayavi2
/DDP_codes/sim_mesh/cube_qd/cube.msh			- Cubical mesh that could be used (by cubeqd.py) for simulating the ground state 

/DDP_codes/sim_mesh/cylindrical_qd/cylnqd.py	- Simulation of wave function using standard volume approach for cylindrical quantum dot 													  geometry mesh generated by Gmsh and visualized using Mayavi2
/DDP_codes/sim_mesh/cylindrical_qd/cyln.msh		- Cylindrical mesh that could be used (by cylnqd.py) for simulating the ground state

/DDP_codes/sim_mesh/spherical_qd/spheqd.py		- Simulation of wave function using standard volume approach for spherical quantum dot 													  geometry mesh generated by Gmsh and visualized using Mayavi2
/DDP_codes/sim_mesh/spherical_qd/sphe.msh		- Spherical mesh that could be used (by spheqd.py) for simulating the ground state


/DDP_codes/sim_lobpcg/1qw_psi_E.py				- First 9 eigen energies and modes for a single square quantum wire
/DDP_codes/sim_lobpcg/1qw_E_vs_lw.py			- First 10 eigen energies for increasing wire sizes
/DDP_codes/sim_lobpcg/4qw_psi_E.py				- First 9 eigen energies and modes when a 4 quantum wires are placed on a substrate
/DDP_codes/sim_lobpcg/4qw_Vout.py				- Eigen energies and modes as the substrate potential is varied
/DDP_codes/sim_lobpcg/4qw_gap.py				- Eigen energies and modes as the gap between the wires is varied


/DDP_codes/tmr/vs_d/tfa_gfa_tmr_vs_d.py			- Transmission probabilities, tunneling conductances and TMR for planar and nanowire tunnel 												  junctions as a function of barrier thickness (depends on "defs.py")
/DDP_codes/tmr/vs_d/defs.py (header)			- Functions to calculate wave vectors, transformation matrices at FM-barrier interfaces and 												  for eigen value solver (has only function definitions)

/DDP_codes/tmr/vs_vb/tfa_gfa_tmr_vs_vb.py		- Transmission probabilities, tunneling conductances and TMR for planar and nanowire tunnel 												  junctions as a function of barrier potential (depends on "defs.py")
/DDP_codes/tmr/vs_vb/defs.py (header)			- Functions to calculate wave vectors, transformation matrices at FM-barrier interfaces and 												  for eigen value solver (has only function definitions)

/DDP_codes/tmr/4qw/4qw_gfa_tmr.py				- Tunneling conductances and TMR for the case with four nanowires placed apart


/DDP_codes/stt/free/spin_nw_pl.py				- Transverse spin current behaviour in planar and nanowire tunnel junction (depends on 													  "defs.py" and "plots.py")
/DDP_codes/stt/free/defs.py (header)			- Function for several Reflection and transmission related parameters (has only function 													  definition)
/DDP_codes/stt/free/plots.py (header)			- Fucntions for several kinds of plots (has only function definitions)

/DDP_codes/stt/dist/qin_qref.py					- Incident and reflected transverse spin current density vs wire size in nm (depends on 												  "defs.py")
/DDP_codes/stt/dist/stt,qtra_qtra_vs_kfx.py		- Spin transfer torque and transverse transmitted spin current (depends on "defs.py")
/DDP_codes/stt/dist/stt_vs_lw.py				- Spin transfer torque for different wire sizes at a particular distance (depends on "defs.py")
/DDP_codes/stt/dist/defs.py (header)			- Functions used for STT when distribution of electrons are considered (has only function 													  definitions)


THE END
